package componentized:filesystem;

world filesystem {
    import latch;
    import wasi:config/store@0.2.0-rc.1;
    import wasi:logging/logging@0.1.0-draft;
    import wasi:filesystem/preopens@0.3.0;
    export wasi:filesystem/preopens@0.3.0;
    import wasi:filesystem/types@0.3.0;
    export wasi:filesystem/types@0.3.0;
}

world filesystem-latch {
    export latch;
}

world filesystem-latch-n {
    export latch;
    import latch1;
    import latch2;
    import latch3;
    import latch4;
    import wasi:filesystem/preopens@0.2.6;
    import wasi:filesystem/types@0.2.6;
}
